// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvbaFcCLCMBr5grwcAUz4uGI0tVdpRSYo',
    appId: '1:386854969207:web:27d73574d4cdd130360b72',
    messagingSenderId: '386854969207',
    projectId: 'lab-13-9-flutter-todo',
    authDomain: 'lab-13-9-flutter-todo.firebaseapp.com',
    storageBucket: 'lab-13-9-flutter-todo.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQ7G5g-8ET-wMeXB0DphXFZsEdIfsV1K4',
    appId: '1:386854969207:android:0bc44779d84b5884360b72',
    messagingSenderId: '386854969207',
    projectId: 'lab-13-9-flutter-todo',
    storageBucket: 'lab-13-9-flutter-todo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCF43TB3MtH0cpEN2t95ID1RSRTQodWG4g',
    appId: '1:386854969207:ios:1941db5a24d3d7d5360b72',
    messagingSenderId: '386854969207',
    projectId: 'lab-13-9-flutter-todo',
    storageBucket: 'lab-13-9-flutter-todo.appspot.com',
    iosBundleId: 'com.example.flutterConDatabase9624',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCF43TB3MtH0cpEN2t95ID1RSRTQodWG4g',
    appId: '1:386854969207:ios:1941db5a24d3d7d5360b72',
    messagingSenderId: '386854969207',
    projectId: 'lab-13-9-flutter-todo',
    storageBucket: 'lab-13-9-flutter-todo.appspot.com',
    iosBundleId: 'com.example.flutterConDatabase9624',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCvbaFcCLCMBr5grwcAUz4uGI0tVdpRSYo',
    appId: '1:386854969207:web:6a09363c3a4d5202360b72',
    messagingSenderId: '386854969207',
    projectId: 'lab-13-9-flutter-todo',
    authDomain: 'lab-13-9-flutter-todo.firebaseapp.com',
    storageBucket: 'lab-13-9-flutter-todo.appspot.com',
  );

}